version: "3.9"

services:
  web:
    build:
      context: .
      args:
        - DATABASE_URL=${DATABASE_URL}
        - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
        - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
    container_name: lingoclone_web
    ports:
      - "3000:3000"
    env_file: .env.local