name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: lingo
          POSTGRES_PASSWORD: lingopass
          POSTGRES_DB: lingodb
        ports: [5432:5432]
      redis:
        image: redis:7-alpine
        ports: ["6379:6379"]

    env:
      PGHOST: localhost
      PGPORT: 5432
      PGUSER: lingo
      PGPASSWORD: lingopass
      PGDATABASE: lingodb
      REDIS_URL: redis://localhost:6379
      NODE_ENV: test

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps & build
        run: |
          npm ci
          npm run build

      - name: Unit tests
        run: npm test

      # ─── build Docker image and push to GHCR on main ──────────
      - name: Log in to GHCR
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push image
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}/web:latest
